fix(refactor(dry)): combine similar window ID lookups, and fix quoting issue

diff --git a/bin/raise-lower-desktop-window b/bin/raise-lower-desktop-window
--- a/bin/raise-lower-desktop-window
+++ b/bin/raise-lower-desktop-window
@@ -69,21 +69,60 @@ get_focused_window_id() {
   local de_name="$1"
 
   if [ "${de_name}" = "GNOME" ]; then
-    get_focused_window_id_Wayland
+    get_window_ids_Wayland ${_is_focused:-true}
   elif [ "${de_name}" = "MATE" ]; then
     get_focused_window_id_XWindow
   fi
 }
 
-get_focused_window_id_Wayland() {
-  if ! gdbus call --session --dest org.gnome.Shell \
-    --object-path /org/gnome/Shell/Extensions/Windows \
-    --method org.gnome.Shell.Extensions.Windows.List \
-    | head -c -4 | tail -c +3 \
-    | jq '.[] | select(.focus == true) | .id' \
+get_window_ids_Wayland() {
+  local _is_focused="${1:-false}"
+
+  local windows_list_parenquoted
+  # E.g., ('{JSON}')
+  if ! windows_list_parenquoted="$(
+    gdbus call --session --dest org.gnome.Shell \
+      --object-path /org/gnome/Shell/Extensions/Windows \
+      --method org.gnome.Shell.Extensions.Windows.List
+  )"; then
+    # SAVVY: check_deps should make this path unreachable.
+    # E.g. — Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod:
+    #   Object does not exist at path “/org/gnome/Shell/Extensions/Foo”
+    alert_missing_gnome_extension_window_calls
+
+    return 1
+  fi
+
+  # Ignore errors, e.g.,
+  #   "Error: GDBus.Error:org.gnome.gjs.JSError.Error: Not found"
+  # though that probably only happens when you're debugging, and you're
+  # manually replaying windows_list you captured previously.
+
+  # Remove leading (tail -c +3) and trailing (head -c -4) parens-quoted:
+  #   (' and ',)
+
+  local windows_list_json
+  windows_list_json="$(
+    echo "${windows_list_parenquoted}" | head -c -4 | tail -c +3
+  )"
+
+  local select_focus=""
+  if ${_is_focused}; then
+    select_focus="select(.focus == true) | "
+  fi
+
+  # Print matching window IDs.
+  if ! echo "${windows_list_json}" \
+    | sed -e 's/\\"/"/g' -e 's/\\\\"/\\"/g' \
+    | jq ".[] | ${select_focus} .id" \
     ; then
 
-    alert_missing_gnome_extension_window_calls
+    # SPIKE/DUNNO: What's an error indicate?
+    # - No focused window? Or no windows at all?
+    >&2 echo "DUNNO: Cannot determine $(
+      ! ${_is_focused} || echo "focused "
+    )windows ID(s) (window-calls)"
+    >&2 echo "${windows_list_json}"
 
     return 1
   fi
@@ -116,31 +155,11 @@ raise_window() {
 #   _humb_print_terminal_window_title_prefixes_Wayland
 # ~/.kit/sh/sh-humble-prompt/lib/show-command-name-in-window-title.sh
 raise_window_Wayland() {
-  local windows_list
-  if ! windows_list="$(
-    gdbus call --session --dest org.gnome.Shell \
-      --object-path /org/gnome/Shell/Extensions/Windows \
-      --method org.gnome.Shell.Extensions.Windows.List
-  )"; then
-    # SAVVY: check_deps makes this path unreachable.
-    # E.g. — Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod:
-    #   Object does not exist at path “/org/gnome/Shell/Extensions/Foo”
-    alert_missing_gnome_extension_window_calls
+  local windows_ids
+  if ! windows_ids="$(get_window_ids_Wayland ${_is_focused:-false})"; then
 
     return 1
   fi
-
-  # Ignore errors, e.g.,
-  #   "Error: GDBus.Error:org.gnome.gjs.JSError.Error: Not found"
-  # though that probably only happens when you're debugging, and you're
-  # manually replaying windows_list you captured previously.
-
-  # Remove leading (tail -c +3) and trailing (head -c -4) parens-quoted:
-  #   (' and ',)
-  local windows_ids
-  windows_ids="$(
-    echo "${windows_list}" | head -c -4 | tail -c +3 | jq '.[] | .id'
-  )"
 
   local windows_details
   windows_details="$(
